[package]
publish = false
name = "import_meta_env_swc"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
rust-ini = "0.19.0"
serde = "1.0.171"
serde_json = "1.0.102"
string_cache = "0.8.7"
swc_core = { version = "0.74.6", features = [
  "ecma_plugin_transform",
  "ecma_ast_serde",
] }

[dev-dependencies]
tempfile = "3.6.0"

# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
