name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  import-meta-env:
    name: "import-meta-env - node@${{ matrix.node_version }}, ${{ matrix.os }}"

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node_version: 16

      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^7

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Check formatting
        run: pnpm prettier --check .

      - name: Build packages
        run: node scripts/build.js

      - name: Install binary
        run: pnpm i

      - name: Test packages
        run: pnpm --recursive --aggregate-output --filter @import-meta-env/* run test

  npm-node-18-examples:
    name: "example - ${{ matrix.example }}, node@${{ matrix.node_version }}, ${{ matrix.os }}"

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        example:
          - "@vue+cli@5-example"
          - "angular-example"
          - "babel-starter-example"
          - "compatibility-example"
          - "create-next-app-example"
          - "create-react-app-example"
          - "create-vue-app-example"
          - "docker-starter-example"
          - "esbuild-starter-example"
          - "jest-example"
          - "mocha-example"
          - "nuxt-bridge-example"
          - "nx-react-example"
          - "process-env-example"
          - "rollup-plugin-babel-example"
          - "rollup-starter-example"
          - "vite-alpine-example"
          - "vite-built-in-import-meta-env-example"
          - "vite-config-build-assets-dir-example"
          - "vite-config-build-out-dir-example"
          - "vite-legacy-example"
          - "vite-preact-example"
          - "vite-react-example"
          - "vite-solid-example"
          - "vite-starter-example"
          - "vite-svelte-example"
          - "vite-vanilla-example"
          - "vite-vanilla-ts-example"
          - "vite-vue-jsx-example"
          - "vite-vue-ts-example"
          - "vitest-example"
          - "webpack-babel-loader-example"
          - "webpack-starter-example"
          - "webpack-ts-loader-example"
        include:
          - os: ubuntu-latest
            node_version: 18

      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^7

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Build packages
        run: pnpm run build

      - name: Pack packages
        run: pnpm run pack

      - name: Test ${{ matrix.example }}
        run: |
          cd packages/examples
          npm i
          cd ${{ matrix.example }}
          npm i
          npm run _test

  npm-node-16-examples:
    name: "example - ${{ matrix.example }}, node@${{ matrix.node_version }}, ${{ matrix.os }}"

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        example:
          - "@vue+cli@4-example"
          - "create-nuxt-app-example"
        include:
          - os: ubuntu-latest
            node_version: 16

      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^7

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Build packages
        run: pnpm run build

      - name: Pack packages
        run: pnpm run pack

      - name: Test ${{ matrix.example }}
        run: |
          cd packages/examples
          npm i
          cd ${{ matrix.example }}
          npm i
          npm run _test

  release:
    name: release

    if: github.ref_name == 'main'

    needs:
      - import-meta-env
      - npm-node-18-examples
      - npm-node-16-examples

    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - babel
          - cli
          - flow
          - typescript
          - unplugin

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^7

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Build packages
        run: pnpm run build

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/${{ matrix.package }}/package.json
          tag: latest
          access: public
          dry-run: false
          check-version: true
          greater-version-only: true

      - name: Tag
        uses: anothrNick/github-tag-action@v1
        if: steps.publish.outputs.type != 'none'
        env:
          CUSTOM_TAG: ${{ matrix.package }}${{ steps.publish.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    name: "docs"

    if: github.ref_name == 'main'

    needs:
      - import-meta-env
      - npm-node-18-examples
      - npm-node-16-examples

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^7

      - name: Install dependencies
        run: pnpm i

      - name: Build docs
        run: pnpm run docs:build

      - name: Commit files
        run: |
          cd docs/.vitepress/dist
          git init
          git branch -m gh-pages
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "docs: deploy"

      - name: Push docs
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: docs/.vitepress/dist
          force: true
